### ISSUE TITLE
Build?

### ISSUE THREAD

**Issue by hugo4715** [Antonin-Deniau/roguelike#1]
Salut, tu pourrait ajouter un dossier contenant un html avec le js compilé?

**Comment by Antonin-Deniau** [comment]
Je vais faire un [blog github] (https://pages.github.com/) Pour pouvoir jouer avec les versions milestone et beta de l'appli, quand elle sera fonctionnelle.

**Comment by hugo4715** [comment]
Cool, quand ca sera fait update le readme, je le check de temp en temp :p

**Comment by Antonin-Deniau** [comment]
Okay ca marche
